export const IDENTITY_ERROR_CODES = {
  INVALID_DNI_FORMAT: 'IDENTITY_INVALID_DNI_FORMAT',
  INVALID_RUC_FORMAT: 'IDENTITY_INVALID_RUC_FORMAT',
  DNI_NOT_FOUND: 'IDENTITY_DNI_NOT_FOUND',
  RUC_NOT_FOUND: 'IDENTITY_RUC_NOT_FOUND',
  RUC_NOT_ACTIVE: 'IDENTITY_RUC_NOT_ACTIVE',
  SERVICE_UNAVAILABLE: 'IDENTITY_SERVICE_UNAVAILABLE',
  PROVIDER_NOT_CONFIGURED: 'IDENTITY_PROVIDER_NOT_CONFIGURED',
} as const;

export type IdentityErrorCode =
  (typeof IDENTITY_ERROR_CODES)[keyof typeof IDENTITY_ERROR_CODES];
