export enum StockMovementType {
  INGRESO = 'INGRESO',
  AJUSTE_POSITIVO = 'AJUSTE_POSITIVO',
  AJUSTE_NEGATIVO = 'AJUSTE_NEGATIVO',
  RESERVA = 'RESERVA',
  LIBERACION = 'LIBERACION',
  VENTA = 'VENTA',
  DEVOLUCION = 'DEVOLUCION',
}
