export const DELIVERY_FEE = 15;

export const STORE_PICKUP_ADDRESS =
  'CAL.GARCI CARBAJAL NRO. 101 INT. A12 CENTRO COMERCIAL LA ESQUINA DEL FUTURO';

export const STORE_BUSINESS_HOURS = 'Lunes a Sábado de 8:00 AM a 8:00 PM';
